"""empty message

Revision ID: 16fc0e6244e5
Revises: 84de64293d46
Create Date: 2021-05-04 21:46:45.022731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fc0e6244e5'
down_revision = '84de64293d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'deleteNumber',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'deleteNumber',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
