"""empty message

Revision ID: 59628b546540
Revises: 11ba319944e8
Create Date: 2021-04-27 03:12:16.977266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59628b546540'
down_revision = '11ba319944e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=120), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
