"""empty message

Revision ID: 84de64293d46
Revises: 1ded0681c1b5
Create Date: 2021-05-04 21:43:29.396538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84de64293d46'
down_revision = '1ded0681c1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('deleteNumber', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'deleteNumber')
    # ### end Alembic commands ###
